services:
  flipper-dispatcher:
    build:
      context: ./flipper-dispatcher
      dockerfile: edge.Dockerfile
    container_name: flipper0-dispatcher
    devices:
      - "/dev/serial/by-id:/dev/serial/by-id"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC_PREFIX=${MQTT_TOPIC_PREFIX:-flipper0}
    restart: unless-stopped
    networks:
      - flipper-net

networks:
  flipper-net:
    driver: bridge